<?php
    
    namespace App\Admin\Controllers;
    
    use App\Models\Industry;
    use Encore\Admin\Controllers\AdminController;
    use Encore\Admin\Controllers\ModelForm;
    use Encore\Admin\Facades\Admin;
    use Encore\Admin\Form;
    use Encore\Admin\Grid;
    use Encore\Admin\Layout\Content;
    use Encore\Admin\Show;
    use Encore\Admin\Traits\AdminBuilder;
    use Encore\Admin\Traits\ModelTree;
    
    class IndustryController extends AdminController
    {
        use ModelForm;
        /**
         * Title for current resource.
         *
         * @var string
         */
        protected $title = '行业列表';
        
        
        public function index(Content $content)
        {
            
            $content->breadcrumb(
                ['text' => '行业列表']
            );
            $content->body(Industry::tree());
            
            return parent::index($content); // TODO: Change the autogenerated stub
        }
        
        public function create(Content $content)
        {
            $content->breadcrumb(
                ['text' => '行业列表', 'url' => '/industries'],
                ['text' => '创建']
            );
            
            return parent::create($content); // TODO: Change the autogenerated stub
        }
        
        public function edit($id, Content $content)
        {
            $content->breadcrumb(
                ['text' => '行业列表', 'url' => '/industries'],
                ['text' => '更新']
            );
            
            return parent::edit($id, $content); // TODO: Change the autogenerated stub
        }
        
        /**
         * Make a grid builder.
         *
         * @return Grid
         */
        protected function grid()
        {
            $grid = new Grid(new Industry);
            $grid->expandFilter();
            $grid->disableExport();
            $grid->model()->where('site_id', site()->get());
            $grid->filter(function ($filter) {
                $filter->disableIdFilter();
                
                $filter->column(1 / 2, function ($filter) {
                    $filter->like('name', '名称');
                });
                $filter->column(1 / 2, function ($filter) {
                    $filter->equal('parent_id', '所属分类')->select(Industry::selectOptions());
                });
                
                
            });
            $grid->actions(function ($actions) {
                $actions->disableView();
            });
            $grid->column('id', __('编码'));
            $grid->column('name', __('名称'));
            $grid->column('sort', __('排序'));
            $grid->column('created_at', __('创建时间'));
            
            return $grid;
        }
        
        /**
         * Make a form builder.
         *
         * @return Form
         */
        protected function form()
        {
            $form = new Form(new Industry);
            $form->disableViewCheck();
            $form->tools(function (Form\Tools $tools) {
                $tools->disableView();
            });
            $form->hidden('site_id')->default(site()->get());
            $form->select('parent_id', __('所属行业'))->options(Industry::selectOptions());
            $form->text('name', __('名称'));
            $form->number('sort', __('排序'))->default(0);
            
            return $form;
        }
    }
